/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurchargeCalculatorRouteImport } from './routes/surcharge-calculator'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as FxSavingsRouteImport } from './routes/fx-savings'
import { Route as FintechsRouteImport } from './routes/fintechs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const SurchargeCalculatorRoute = SurchargeCalculatorRouteImport.update({
  id: '/surcharge-calculator',
  path: '/surcharge-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FxSavingsRoute = FxSavingsRouteImport.update({
  id: '/fx-savings',
  path: '/fx-savings',
  getParentRoute: () => rootRouteImport,
} as any)
const FintechsRoute = FintechsRouteImport.update({
  id: '/fintechs',
  path: '/fintechs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/fintechs': typeof FintechsRoute
  '/fx-savings': typeof FxSavingsRoute
  '/marketplace': typeof MarketplaceRoute
  '/surcharge-calculator': typeof SurchargeCalculatorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/fintechs': typeof FintechsRoute
  '/fx-savings': typeof FxSavingsRoute
  '/marketplace': typeof MarketplaceRoute
  '/surcharge-calculator': typeof SurchargeCalculatorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/fintechs': typeof FintechsRoute
  '/fx-savings': typeof FxSavingsRoute
  '/marketplace': typeof MarketplaceRoute
  '/surcharge-calculator': typeof SurchargeCalculatorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/contact'
    | '/fintechs'
    | '/fx-savings'
    | '/marketplace'
    | '/surcharge-calculator'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/contact'
    | '/fintechs'
    | '/fx-savings'
    | '/marketplace'
    | '/surcharge-calculator'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/contact'
    | '/fintechs'
    | '/fx-savings'
    | '/marketplace'
    | '/surcharge-calculator'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  FintechsRoute: typeof FintechsRoute
  FxSavingsRoute: typeof FxSavingsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SurchargeCalculatorRoute: typeof SurchargeCalculatorRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surcharge-calculator': {
      id: '/surcharge-calculator'
      path: '/surcharge-calculator'
      fullPath: '/surcharge-calculator'
      preLoaderRoute: typeof SurchargeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx-savings': {
      id: '/fx-savings'
      path: '/fx-savings'
      fullPath: '/fx-savings'
      preLoaderRoute: typeof FxSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fintechs': {
      id: '/fintechs'
      path: '/fintechs'
      fullPath: '/fintechs'
      preLoaderRoute: typeof FintechsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  FintechsRoute: FintechsRoute,
  FxSavingsRoute: FxSavingsRoute,
  MarketplaceRoute: MarketplaceRoute,
  SurchargeCalculatorRoute: SurchargeCalculatorRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
